{% set name = "keras-spiking" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/keras-spiking-{{ version }}.tar.gz
  sha256: 7e729ff7102ee4a9fcb3901aa0763164ff8ea780b8482101c01d8cca14f8bde4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - packaging
    - python >={{ python_min }}
    - tensorflow >=2.1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - keras_spiking

about:
  home: https://www.nengo.ai/keras-spiking
  summary: Spiking neuron integration for Keras
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
